# Generated by Django 5.0 on 2024-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('leader', 'cohort leader'), ('deputy', 'vice leader'), ('secretary', 'secretary'), ('president', 'president'), ('member', 'member')], default='member', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
