# Generated by Django 5.0 on 2024-10-30 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_date_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-date_join']},
        ),
        migrations.AlterField(
            model_name='cohortgroup',
            name='student',
            field=models.ManyToManyField(related_name='cohortgroup', to='student.student'),
        ),
        migrations.AlterField(
            model_name='program',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.student'),
        ),
    ]
