# Generated by Django 5.0 on 2024-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_options_alter_cohortgroup_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
