# Generated by Django 5.0 on 2024-11-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_contact_phone_student_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('student_type__in', ['president', 'secretary'])), fields=('student_type',), name='unique_roles'),
        ),
    ]
